/** UI strings for the card and the settings page. One object so a locale swap is one file. */
export const COPY = {
  searching: 'Searching refkit sources…',
  refsFor: (count: number, query: string) => `${count} reference${count === 1 ? '' : 's'} for “${query}”`,
  intent: (intent: string) => `intent: ${intent}`,
  more: 'more available — ask for the next page',
  failed: (n: number) => `${n} source${n === 1 ? '' : 's'} failed`,
  skipped: (n: number) => `${n} skipped`,
  open: 'Open',
  copyCredit: 'Copy credit',
  copied: 'Copied',
  copyFailed: 'Select and copy:',
  empty: 'No results. Try broader terms, another modality, or fewer controls.',
  legend: 'Verdict:',
  untitled: '(untitled)',
  settings: {
    summary: (configured: number, total: number) => `License-aware reference search · ${configured} of ${total} keys set`,
    // The shared form frame.
    unavailable: 'refkit is not running, so it cannot be configured right now.',
    readOnly: 'This deployment stores settings read-only.',
    saveFailed: 'The deployment did not accept these values; they were left for you to correct.',
    save: 'Save',
    saving: 'Saving…',
    overridden: 'Overridden',
    reset: 'Reset to default',
    // API keys.
    keysHeading: 'API keys',
    keysNote: 'Each key enables the sources named beside it; keyless sources need none. Keys are stored in plain text in this profile’s cordis.patch.yml (file mode 0600) and apply on the next search.',
    keyHint: (env: readonly string[]) => `Leave blank to keep the stored key. Environment fallback: ${env.join(' / ')}.`,
    keySet: 'Set',
    keyUnset: 'Not set',
    remove: 'Remove',
    removeLabel: (label: string) => `Remove the ${label} key`,
    removing: 'Removing…',
    removeBlocked: 'Save your other edits first: removing a key writes immediately.',
    removeFailed: 'Not removed; try again.',
    // Search tuning.
    searchHeading: 'Search',
    limit: 'Results per call',
    limitHint: 'Also caps per-item detail fetches for met, rijksmuseum and polyhaven.',
    poolFactor: 'Fusion pool factor',
    poolFactorHint: 'Rank-fusion pool multiplier.',
    deadlineMs: 'Search deadline (ms)',
    deadlineMsHint: 'Whole-search deadline.',
    timeoutMs: 'Per-source timeout (ms)',
    timeoutMsHint: 'How long one source may take.',
    range: (hint: string, bounds: { min: number; max: number; default: number }) => `${hint} ${bounds.min}–${bounds.max}, default ${bounds.default}.`,
    invalidRange: (bounds: { min: number; max: number }) => `Enter a whole number from ${bounds.min} to ${bounds.max}, or leave blank for the default.`,
    sources: 'Sources',
    sourcesHint: 'Comma-separated provider ids. A keyed source also needs its key.',
    sourcesPlaceholder: 'empty = all enabled sources',
    sourcesHelp: 'Source ids',
    sourcesInvalid: 'Unknown source id. Use the ids listed under the info button.',
    userAgent: 'User-Agent',
    userAgentHint: 'Sent with provider requests. Blank uses refkit-dsh-plugin/<version>.',
    rerank: 'Lexical rerank',
    rerankHint: 'Rerank fused results over title, description, tags and excerpt.',
    sourceConfidence: 'Source confidence',
    sourceConfidenceHint: 'Down-weight sources whose batch never mentions the query.',
  },
} as const
